version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: client/Dockerfile
            args:
                - VITE_BASE_URL=${VITE_BASE_URL}
        ports:
            - 80:80
        healthcheck:
            test: "CMD wget -q -O /dev/null http://localhost || exit 1"
            interval: 30s
            timeout: 5s
            retries: 3
        depends_on:
            hive:
                condition: service_healthy
        networks:
            - codraw-local

    hive:
        build:
            context: .
            dockerfile: hive/Dockerfile
        ports:
            - ${PORT}:${PORT}
        environment:
            - PORT=${PORT}
        restart: always
        healthcheck:
            test: "curl --fail http://localhost:${PORT} || exit 1"
            interval: 30s
            timeout: 5s
            retries: 3
        networks:
            - codraw-local

networks:
    codraw-local:
